<?php

/**
 * @file
 * Contains generating_entities_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function generating_entities_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the generating_entities_module module.
    case 'help.page.generating_entities_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Training in generating entities') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function generating_entities_module_theme($existing, $type, $theme, $path) { 
  return [
    'my_template' => [
      'variables' => [
        'articles' => NULL		
      ],
    ],
  ];
}
